---
editor_options:
  chunk_output_type: console
fontsize: 11pt
output:
  pdf_document:
    toc: yes
    includes:
      in_header: preamble.tex
    number_sections: yes
  html_document:
    df_print: paged
documentclass: article
toc-title: "Supplemental Information"
---

```{r setup, include=FALSE}
#knitr::opts_knit$set(root.dir="../")
knitr::opts_chunk$set(fig.width=10, fig.height=8, warning=FALSE, message=FALSE,cache=FALSE)
options(tinytex.verbose = TRUE)
```

\pagestyle{fancy}
\fancyhead{}
\renewcommand{\headrulewidth}{0pt}
\fancyfoot{}
\fancyfoot[R]{\thepage}

\newcommand{\addsection}[3]{\addtocontents{toc}{\protect\contentsline{section}{\protect\numberline{#1}#2}{#3}{}}}
\newcommand{\addsubsection}[3]{\addtocontents{toc}{\protect\contentsline{subsection}{\protect\numberline{#1}#2}{#3}{}}}

\addsection{1}{Supplemental Figures}{2}
\addsubsection{}{Figure S1. Factors resulting in enrichment of observed variant prevalence.}{2}
\addsubsection{}{Figure S2. Parameters affecting the coefficient of detection.}{3}
\addsubsection{}{Figure S3. Validation of the binomial sampling approximation.}{4}
\addsubsection{}{Figure S4. Sample size needed for variant detection and prevalence estimation with 50\% confidence.}{5}
\addsubsection{}{Figure S5. Sample size needed for detection of a variant growing in prevalence.}{6}
\addsection{2}{Supplemental Text 1: Derivations}{7}
\addsubsection{}{Calculating variant prevalence from an observed sample}{7}
\addsubsection{}{Sample size calculations with continuous surveillance}{9}
\addsection{3}{Supplemental Text 2: Worked Example}{12}
\addsubsection{}{Variant-specific parameter estimation}{12}
\addsubsection{}{The coefficient of detection ratio}{13}
\addsubsection{}{Sample size calculations}{14}
\addsubsection{}{Estimating the probability of detection}{15}
\addsection{4}{Supplemental Data 1: Variant Sampling Workbook (.xlsx)}{}
